import collections
import sys
print(sys.version)

input = """
>>> result:  success
{
    'result': {
        'status': 'success',
        'errorCode': None,
        'errorMessage': None,
        'errorCategory': None
    },
    'products': {
        'product': [
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('800.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a5ea48>, <Element id at 0x7f42d6a5ea88>, <Element price at 0x7f42d6a5eac8>, <Element productSellerCode at 0x7f42d6a5eb08>, <Element approvalStatus at 0x7f42d6a5eb48>, <Element saleStatus at 0x7f42d6a5eb88>, <Element stockItems at 0x7f42d6a5ebc8>, <Element subtitle at 0x7f42d6a5ec08>, <Element title at 0x7f42d6a5ec48>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('264.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a601c8>, <Element id at 0x7f42d6a60208>, <Element price at 0x7f42d6a60248>, <Element productSellerCode at 0x7f42d6a60288>, <Element approvalStatus at 0x7f42d6a602c8>, <Element saleStatus at 0x7f42d6a60308>, <Element stockItems at 0x7f42d6a60348>, <Element subtitle at 0x7f42d6a60388>, <Element title at 0x7f42d6a603c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('264.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a60448>, <Element id at 0x7f42d6a60488>, <Element price at 0x7f42d6a604c8>, <Element productSellerCode at 0x7f42d6a60508>, <Element approvalStatus at 0x7f42d6a60548>, <Element saleStatus at 0x7f42d6a60588>, <Element stockItems at 0x7f42d6a605c8>, <Element subtitle at 0x7f42d6a60608>, <Element title at 0x7f42d6a60648>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('96.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a606c8>, <Element id at 0x7f42d6a60708>, <Element price at 0x7f42d6a60748>, <Element productSellerCode at 0x7f42d6a60788>, <Element approvalStatus at 0x7f42d6a607c8>, <Element saleStatus at 0x7f42d6a60808>, <Element stockItems at 0x7f42d6a60848>, <Element subtitle at 0x7f42d6a60888>, <Element title at 0x7f42d6a608c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('96.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a60948>, <Element id at 0x7f42d6a60988>, <Element price at 0x7f42d6a609c8>, <Element productSellerCode at 0x7f42d6a60a08>, <Element approvalStatus at 0x7f42d6a60a48>, <Element saleStatus at 0x7f42d6a60a88>, <Element stockItems at 0x7f42d6a60ac8>, <Element subtitle at 0x7f42d6a60b08>, <Element title at 0x7f42d6a60b48>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('72.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a60bc8>, <Element id at 0x7f42d6a60c08>, <Element price at 0x7f42d6a60c48>, <Element productSellerCode at 0x7f42d6a60c88>, <Element approvalStatus at 0x7f42d6a60cc8>, <Element saleStatus at 0x7f42d6a60d08>, <Element stockItems at 0x7f42d6a60d48>, <Element subtitle at 0x7f42d6a60d88>, <Element title at 0x7f42d6a60dc8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('72.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a60e48>, <Element id at 0x7f42d6a60e88>, <Element price at 0x7f42d6a60ec8>, <Element productSellerCode at 0x7f42d6a60f08>, <Element approvalStatus at 0x7f42d6a60f48>, <Element saleStatus at 0x7f42d6a60f88>, <Element stockItems at 0x7f42d6a60fc8>, <Element subtitle at 0x7f42d6a62048>, <Element title at 0x7f42d6a62088>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('480.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a62108>, <Element id at 0x7f42d6a62148>, <Element price at 0x7f42d6a62188>, <Element productSellerCode at 0x7f42d6a621c8>, <Element approvalStatus at 0x7f42d6a62208>, <Element saleStatus at 0x7f42d6a62248>, <Element stockItems at 0x7f42d6a62288>, <Element subtitle at 0x7f42d6a622c8>, <Element title at 0x7f42d6a62308>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('480.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a62388>, <Element id at 0x7f42d6a623c8>, <Element price at 0x7f42d6a62408>, <Element productSellerCode at 0x7f42d6a62448>, <Element approvalStatus at 0x7f42d6a62488>, <Element saleStatus at 0x7f42d6a624c8>, <Element stockItems at 0x7f42d6a62508>, <Element subtitle at 0x7f42d6a62548>, <Element title at 0x7f42d6a62588>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('120.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a62608>, <Element id at 0x7f42d6a62648>, <Element price at 0x7f42d6a62688>, <Element productSellerCode at 0x7f42d6a626c8>, <Element approvalStatus at 0x7f42d6a62708>, <Element saleStatus at 0x7f42d6a62748>, <Element stockItems at 0x7f42d6a62788>, <Element subtitle at 0x7f42d6a627c8>, <Element title at 0x7f42d6a62808>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('120.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a62888>, <Element id at 0x7f42d6a628c8>, <Element price at 0x7f42d6a62908>, <Element productSellerCode at 0x7f42d6a62948>, <Element approvalStatus at 0x7f42d6a62988>, <Element saleStatus at 0x7f42d6a629c8>, <Element stockItems at 0x7f42d6a62a08>, <Element subtitle at 0x7f42d6a62a48>, <Element title at 0x7f42d6a62a88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('84.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a62b08>, <Element id at 0x7f42d6a62b48>, <Element price at 0x7f42d6a62b88>, <Element productSellerCode at 0x7f42d6a62bc8>, <Element approvalStatus at 0x7f42d6a62c08>, <Element saleStatus at 0x7f42d6a62c48>, <Element stockItems at 0x7f42d6a62c88>, <Element subtitle at 0x7f42d6a62cc8>, <Element title at 0x7f42d6a62d08>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('84.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a62d88>, <Element id at 0x7f42d6a62dc8>, <Element price at 0x7f42d6a62e08>, <Element productSellerCode at 0x7f42d6a62e48>, <Element approvalStatus at 0x7f42d6a62e88>, <Element saleStatus at 0x7f42d6a62ec8>, <Element stockItems at 0x7f42d6a62f08>, <Element subtitle at 0x7f42d6a62f48>, <Element title at 0x7f42d6a62f88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('120.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a64048>, <Element id at 0x7f42d6a64088>, <Element price at 0x7f42d6a640c8>, <Element productSellerCode at 0x7f42d6a64108>, <Element approvalStatus at 0x7f42d6a64148>, <Element saleStatus at 0x7f42d6a64188>, <Element stockItems at 0x7f42d6a641c8>, <Element subtitle at 0x7f42d6a64208>, <Element title at 0x7f42d6a64248>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('180.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a642c8>, <Element id at 0x7f42d6a64308>, <Element price at 0x7f42d6a64348>, <Element productSellerCode at 0x7f42d6a64388>, <Element approvalStatus at 0x7f42d6a643c8>, <Element saleStatus at 0x7f42d6a64408>, <Element stockItems at 0x7f42d6a64448>, <Element subtitle at 0x7f42d6a64488>, <Element title at 0x7f42d6a644c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a64508>, <Element id at 0x7f42d6a64548>, <Element price at 0x7f42d6a64588>, <Element productSellerCode at 0x7f42d6a645c8>, <Element approvalStatus at 0x7f42d6a64608>, <Element saleStatus at 0x7f42d6a64648>, <Element stockItems at 0x7f42d6a64688>, <Element subtitle at 0x7f42d6a646c8>, <Element title at 0x7f42d6a64708>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('168.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a64788>, <Element id at 0x7f42d6a647c8>, <Element price at 0x7f42d6a64808>, <Element productSellerCode at 0x7f42d6a64848>, <Element approvalStatus at 0x7f42d6a64888>, <Element saleStatus at 0x7f42d6a648c8>, <Element stockItems at 0x7f42d6a64908>, <Element subtitle at 0x7f42d6a64948>, <Element title at 0x7f42d6a64988>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('168.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a64a08>, <Element id at 0x7f42d6a64a48>, <Element price at 0x7f42d6a64a88>, <Element productSellerCode at 0x7f42d6a64ac8>, <Element approvalStatus at 0x7f42d6a64b08>, <Element saleStatus at 0x7f42d6a64b48>, <Element stockItems at 0x7f42d6a64b88>, <Element subtitle at 0x7f42d6a64bc8>, <Element title at 0x7f42d6a64c08>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('120.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a64c88>, <Element id at 0x7f42d6a64cc8>, <Element price at 0x7f42d6a64d08>, <Element productSellerCode at 0x7f42d6a64d48>, <Element approvalStatus at 0x7f42d6a64d88>, <Element saleStatus at 0x7f42d6a64dc8>, <Element stockItems at 0x7f42d6a64e08>, <Element subtitle at 0x7f42d6a64e48>, <Element title at 0x7f42d6a64e88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('120.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a64f08>, <Element id at 0x7f42d6a64f48>, <Element price at 0x7f42d6a64f88>, <Element productSellerCode at 0x7f42d6a64fc8>, <Element approvalStatus at 0x7f42d6a65048>, <Element saleStatus at 0x7f42d6a65088>, <Element stockItems at 0x7f42d6a650c8>, <Element subtitle at 0x7f42d6a65108>, <Element title at 0x7f42d6a65148>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a651c8>, <Element id at 0x7f42d6a65208>, <Element price at 0x7f42d6a65248>, <Element productSellerCode at 0x7f42d6a65288>, <Element approvalStatus at 0x7f42d6a652c8>, <Element saleStatus at 0x7f42d6a65308>, <Element stockItems at 0x7f42d6a65348>, <Element subtitle at 0x7f42d6a65388>, <Element title at 0x7f42d6a653c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a65448>, <Element id at 0x7f42d6a65488>, <Element price at 0x7f42d6a654c8>, <Element productSellerCode at 0x7f42d6a65508>, <Element approvalStatus at 0x7f42d6a65548>, <Element saleStatus at 0x7f42d6a65588>, <Element stockItems at 0x7f42d6a655c8>, <Element subtitle at 0x7f42d6a65608>, <Element title at 0x7f42d6a65648>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a656c8>, <Element id at 0x7f42d6a65708>, <Element price at 0x7f42d6a65748>, <Element productSellerCode at 0x7f42d6a65788>, <Element approvalStatus at 0x7f42d6a657c8>, <Element saleStatus at 0x7f42d6a65808>, <Element stockItems at 0x7f42d6a65848>, <Element subtitle at 0x7f42d6a65888>, <Element title at 0x7f42d6a658c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a65948>, <Element id at 0x7f42d6a65988>, <Element price at 0x7f42d6a659c8>, <Element productSellerCode at 0x7f42d6a65a08>, <Element approvalStatus at 0x7f42d6a65a48>, <Element saleStatus at 0x7f42d6a65a88>, <Element stockItems at 0x7f42d6a65ac8>, <Element subtitle at 0x7f42d6a65b08>, <Element title at 0x7f42d6a65b48>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a65bc8>, <Element id at 0x7f42d6a65c08>, <Element price at 0x7f42d6a65c48>, <Element productSellerCode at 0x7f42d6a65c88>, <Element approvalStatus at 0x7f42d6a65cc8>, <Element saleStatus at 0x7f42d6a65d08>, <Element stockItems at 0x7f42d6a65d48>, <Element subtitle at 0x7f42d6a65d88>, <Element title at 0x7f42d6a65dc8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a65e48>, <Element id at 0x7f42d6a65e88>, <Element price at 0x7f42d6a65ec8>, <Element productSellerCode at 0x7f42d6a65f08>, <Element approvalStatus at 0x7f42d6a65f48>, <Element saleStatus at 0x7f42d6a65f88>, <Element stockItems at 0x7f42d6a65fc8>, <Element subtitle at 0x7f42d6a66048>, <Element title at 0x7f42d6a66088>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a66108>, <Element id at 0x7f42d6a66148>, <Element price at 0x7f42d6a66188>, <Element productSellerCode at 0x7f42d6a661c8>, <Element approvalStatus at 0x7f42d6a66208>, <Element saleStatus at 0x7f42d6a66248>, <Element stockItems at 0x7f42d6a66288>, <Element subtitle at 0x7f42d6a662c8>, <Element title at 0x7f42d6a66308>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a66388>, <Element id at 0x7f42d6a663c8>, <Element price at 0x7f42d6a66408>, <Element productSellerCode at 0x7f42d6a66448>, <Element approvalStatus at 0x7f42d6a66488>, <Element saleStatus at 0x7f42d6a664c8>, <Element stockItems at 0x7f42d6a66508>, <Element subtitle at 0x7f42d6a66548>, <Element title at 0x7f42d6a66588>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('168.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a66608>, <Element id at 0x7f42d6a66648>, <Element price at 0x7f42d6a66688>, <Element productSellerCode at 0x7f42d6a666c8>, <Element approvalStatus at 0x7f42d6a66708>, <Element saleStatus at 0x7f42d6a66748>, <Element stockItems at 0x7f42d6a66788>, <Element subtitle at 0x7f42d6a667c8>, <Element title at 0x7f42d6a66808>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('168.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a66888>, <Element id at 0x7f42d6a668c8>, <Element price at 0x7f42d6a66908>, <Element productSellerCode at 0x7f42d6a66948>, <Element approvalStatus at 0x7f42d6a66988>, <Element saleStatus at 0x7f42d6a669c8>, <Element stockItems at 0x7f42d6a66a08>, <Element subtitle at 0x7f42d6a66a48>, <Element title at 0x7f42d6a66a88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a66b08>, <Element id at 0x7f42d6a66b48>, <Element price at 0x7f42d6a66b88>, <Element productSellerCode at 0x7f42d6a66bc8>, <Element approvalStatus at 0x7f42d6a66c08>, <Element saleStatus at 0x7f42d6a66c48>, <Element stockItems at 0x7f42d6a66c88>, <Element subtitle at 0x7f42d6a66cc8>, <Element title at 0x7f42d6a66d08>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a66d88>, <Element id at 0x7f42d6a66dc8>, <Element price at 0x7f42d6a66e08>, <Element productSellerCode at 0x7f42d6a66e48>, <Element approvalStatus at 0x7f42d6a66e88>, <Element saleStatus at 0x7f42d6a66ec8>, <Element stockItems at 0x7f42d6a66f08>, <Element subtitle at 0x7f42d6a66f48>, <Element title at 0x7f42d6a66f88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a69048>, <Element id at 0x7f42d6a69088>, <Element price at 0x7f42d6a690c8>, <Element productSellerCode at 0x7f42d6a69108>, <Element approvalStatus at 0x7f42d6a69148>, <Element saleStatus at 0x7f42d6a69188>, <Element stockItems at 0x7f42d6a691c8>, <Element subtitle at 0x7f42d6a69208>, <Element title at 0x7f42d6a69248>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a692c8>, <Element id at 0x7f42d6a69308>, <Element price at 0x7f42d6a69348>, <Element productSellerCode at 0x7f42d6a69388>, <Element approvalStatus at 0x7f42d6a693c8>, <Element saleStatus at 0x7f42d6a69408>, <Element stockItems at 0x7f42d6a69448>, <Element subtitle at 0x7f42d6a69488>, <Element title at 0x7f42d6a694c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a69548>, <Element id at 0x7f42d6a69588>, <Element price at 0x7f42d6a695c8>, <Element productSellerCode at 0x7f42d6a69608>, <Element approvalStatus at 0x7f42d6a69648>, <Element saleStatus at 0x7f42d6a69688>, <Element stockItems at 0x7f42d6a696c8>, <Element subtitle at 0x7f42d6a69708>, <Element title at 0x7f42d6a69748>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a697c8>, <Element id at 0x7f42d6a69808>, <Element price at 0x7f42d6a69848>, <Element productSellerCode at 0x7f42d6a69888>, <Element approvalStatus at 0x7f42d6a698c8>, <Element saleStatus at 0x7f42d6a69908>, <Element stockItems at 0x7f42d6a69948>, <Element subtitle at 0x7f42d6a69988>, <Element title at 0x7f42d6a699c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a69a48>, <Element id at 0x7f42d6a69a88>, <Element price at 0x7f42d6a69ac8>, <Element productSellerCode at 0x7f42d6a69b08>, <Element approvalStatus at 0x7f42d6a69b48>, <Element saleStatus at 0x7f42d6a69b88>, <Element stockItems at 0x7f42d6a69bc8>, <Element subtitle at 0x7f42d6a69c08>, <Element title at 0x7f42d6a69c48>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a69cc8>, <Element id at 0x7f42d6a69d08>, <Element price at 0x7f42d6a69d48>, <Element productSellerCode at 0x7f42d6a69d88>, <Element approvalStatus at 0x7f42d6a69dc8>, <Element saleStatus at 0x7f42d6a69e08>, <Element stockItems at 0x7f42d6a69e48>, <Element subtitle at 0x7f42d6a69e88>, <Element title at 0x7f42d6a69ec8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a69f48>, <Element id at 0x7f42d6a69f88>, <Element price at 0x7f42d6a69fc8>, <Element productSellerCode at 0x7f42d6a6a048>, <Element approvalStatus at 0x7f42d6a6a088>, <Element saleStatus at 0x7f42d6a6a0c8>, <Element stockItems at 0x7f42d6a6a108>, <Element subtitle at 0x7f42d6a6a148>, <Element title at 0x7f42d6a6a188>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6a208>, <Element id at 0x7f42d6a6a248>, <Element price at 0x7f42d6a6a288>, <Element productSellerCode at 0x7f42d6a6a2c8>, <Element approvalStatus at 0x7f42d6a6a308>, <Element saleStatus at 0x7f42d6a6a348>, <Element stockItems at 0x7f42d6a6a388>, <Element subtitle at 0x7f42d6a6a3c8>, <Element title at 0x7f42d6a6a408>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6a488>, <Element id at 0x7f42d6a6a4c8>, <Element price at 0x7f42d6a6a508>, <Element productSellerCode at 0x7f42d6a6a548>, <Element approvalStatus at 0x7f42d6a6a588>, <Element saleStatus at 0x7f42d6a6a5c8>, <Element stockItems at 0x7f42d6a6a608>, <Element subtitle at 0x7f42d6a6a648>, <Element title at 0x7f42d6a6a688>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('240.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6a708>, <Element id at 0x7f42d6a6a748>, <Element price at 0x7f42d6a6a788>, <Element productSellerCode at 0x7f42d6a6a7c8>, <Element approvalStatus at 0x7f42d6a6a808>, <Element saleStatus at 0x7f42d6a6a848>, <Element stockItems at 0x7f42d6a6a888>, <Element subtitle at 0x7f42d6a6a8c8>, <Element title at 0x7f42d6a6a908>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('360.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6a988>, <Element id at 0x7f42d6a6a9c8>, <Element price at 0x7f42d6a6aa08>, <Element productSellerCode at 0x7f42d6a6aa48>, <Element approvalStatus at 0x7f42d6a6aa88>, <Element saleStatus at 0x7f42d6a6aac8>, <Element stockItems at 0x7f42d6a6ab08>, <Element subtitle at 0x7f42d6a6ab48>, <Element title at 0x7f42d6a6ab88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('360.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6ac08>, <Element id at 0x7f42d6a6ac48>, <Element price at 0x7f42d6a6ac88>, <Element productSellerCode at 0x7f42d6a6acc8>, <Element approvalStatus at 0x7f42d6a6ad08>, <Element saleStatus at 0x7f42d6a6ad48>, <Element stockItems at 0x7f42d6a6ad88>, <Element subtitle at 0x7f42d6a6adc8>, <Element title at 0x7f42d6a6ae08>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('69.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6ae88>, <Element id at 0x7f42d6a6aec8>, <Element price at 0x7f42d6a6af08>, <Element productSellerCode at 0x7f42d6a6af48>, <Element approvalStatus at 0x7f42d6a6af88>, <Element saleStatus at 0x7f42d6a6afc8>, <Element stockItems at 0x7f42d6a6b048>, <Element subtitle at 0x7f42d6a6b088>, <Element title at 0x7f42d6a6b0c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('180.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6b148>, <Element id at 0x7f42d6a6b188>, <Element price at 0x7f42d6a6b1c8>, <Element productSellerCode at 0x7f42d6a6b208>, <Element approvalStatus at 0x7f42d6a6b248>, <Element saleStatus at 0x7f42d6a6b288>, <Element stockItems at 0x7f42d6a6b2c8>, <Element subtitle at 0x7f42d6a6b308>, <Element title at 0x7f42d6a6b348>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('180.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6b3c8>, <Element id at 0x7f42d6a6b408>, <Element price at 0x7f42d6a6b448>, <Element productSellerCode at 0x7f42d6a6b488>, <Element approvalStatus at 0x7f42d6a6b4c8>, <Element saleStatus at 0x7f42d6a6b508>, <Element stockItems at 0x7f42d6a6b548>, <Element subtitle at 0x7f42d6a6b588>, <Element title at 0x7f42d6a6b5c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('144.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6b648>, <Element id at 0x7f42d6a6b688>, <Element price at 0x7f42d6a6b6c8>, <Element productSellerCode at 0x7f42d6a6b708>, <Element approvalStatus at 0x7f42d6a6b748>, <Element saleStatus at 0x7f42d6a6b788>, <Element stockItems at 0x7f42d6a6b7c8>, <Element subtitle at 0x7f42d6a6b808>, <Element title at 0x7f42d6a6b848>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('144.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6b8c8>, <Element id at 0x7f42d6a6b908>, <Element price at 0x7f42d6a6b948>, <Element productSellerCode at 0x7f42d6a6b988>, <Element approvalStatus at 0x7f42d6a6b9c8>, <Element saleStatus at 0x7f42d6a6ba08>, <Element stockItems at 0x7f42d6a6ba48>, <Element subtitle at 0x7f42d6a6ba88>, <Element title at 0x7f42d6a6bac8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('408.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6bb48>, <Element id at 0x7f42d6a6bb88>, <Element price at 0x7f42d6a6bbc8>, <Element productSellerCode at 0x7f42d6a6bc08>, <Element approvalStatus at 0x7f42d6a6bc48>, <Element saleStatus at 0x7f42d6a6bc88>, <Element stockItems at 0x7f42d6a6bcc8>, <Element subtitle at 0x7f42d6a6bd08>, <Element title at 0x7f42d6a6bd48>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('408.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6bdc8>, <Element id at 0x7f42d6a6be08>, <Element price at 0x7f42d6a6be48>, <Element productSellerCode at 0x7f42d6a6be88>, <Element approvalStatus at 0x7f42d6a6bec8>, <Element saleStatus at 0x7f42d6a6bf08>, <Element stockItems at 0x7f42d6a6bf48>, <Element subtitle at 0x7f42d6a6bf88>, <Element title at 0x7f42d6a6bfc8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('360.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6d088>, <Element id at 0x7f42d6a6d0c8>, <Element price at 0x7f42d6a6d108>, <Element productSellerCode at 0x7f42d6a6d148>, <Element approvalStatus at 0x7f42d6a6d188>, <Element saleStatus at 0x7f42d6a6d1c8>, <Element stockItems at 0x7f42d6a6d208>, <Element subtitle at 0x7f42d6a6d248>, <Element title at 0x7f42d6a6d288>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('360.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6d308>, <Element id at 0x7f42d6a6d348>, <Element price at 0x7f42d6a6d388>, <Element productSellerCode at 0x7f42d6a6d3c8>, <Element approvalStatus at 0x7f42d6a6d408>, <Element saleStatus at 0x7f42d6a6d448>, <Element stockItems at 0x7f42d6a6d488>, <Element subtitle at 0x7f42d6a6d4c8>, <Element title at 0x7f42d6a6d508>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('420.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6d588>, <Element id at 0x7f42d6a6d5c8>, <Element price at 0x7f42d6a6d608>, <Element productSellerCode at 0x7f42d6a6d648>, <Element approvalStatus at 0x7f42d6a6d688>, <Element saleStatus at 0x7f42d6a6d6c8>, <Element stockItems at 0x7f42d6a6d708>, <Element subtitle at 0x7f42d6a6d748>, <Element title at 0x7f42d6a6d788>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('420.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6d808>, <Element id at 0x7f42d6a6d848>, <Element price at 0x7f42d6a6d888>, <Element productSellerCode at 0x7f42d6a6d8c8>, <Element approvalStatus at 0x7f42d6a6d908>, <Element saleStatus at 0x7f42d6a6d948>, <Element stockItems at 0x7f42d6a6d988>, <Element subtitle at 0x7f42d6a6d9c8>, <Element title at 0x7f42d6a6da08>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('336.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6da88>, <Element id at 0x7f42d6a6dac8>, <Element price at 0x7f42d6a6db08>, <Element productSellerCode at 0x7f42d6a6db48>, <Element approvalStatus at 0x7f42d6a6db88>, <Element saleStatus at 0x7f42d6a6dbc8>, <Element stockItems at 0x7f42d6a6dc08>, <Element subtitle at 0x7f42d6a6dc48>, <Element title at 0x7f42d6a6dc88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('336.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6dd08>, <Element id at 0x7f42d6a6dd48>, <Element price at 0x7f42d6a6dd88>, <Element productSellerCode at 0x7f42d6a6ddc8>, <Element approvalStatus at 0x7f42d6a6de08>, <Element saleStatus at 0x7f42d6a6de48>, <Element stockItems at 0x7f42d6a6de88>, <Element subtitle at 0x7f42d6a6dec8>, <Element title at 0x7f42d6a6df08>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('408.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6df88>, <Element id at 0x7f42d6a6dfc8>, <Element price at 0x7f42d6a6e048>, <Element productSellerCode at 0x7f42d6a6e088>, <Element approvalStatus at 0x7f42d6a6e0c8>, <Element saleStatus at 0x7f42d6a6e108>, <Element stockItems at 0x7f42d6a6e148>, <Element subtitle at 0x7f42d6a6e188>, <Element title at 0x7f42d6a6e1c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('408.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6e248>, <Element id at 0x7f42d6a6e288>, <Element price at 0x7f42d6a6e2c8>, <Element productSellerCode at 0x7f42d6a6e308>, <Element approvalStatus at 0x7f42d6a6e348>, <Element saleStatus at 0x7f42d6a6e388>, <Element stockItems at 0x7f42d6a6e3c8>, <Element subtitle at 0x7f42d6a6e408>, <Element title at 0x7f42d6a6e448>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('144.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6e4c8>, <Element id at 0x7f42d6a6e508>, <Element price at 0x7f42d6a6e548>, <Element productSellerCode at 0x7f42d6a6e588>, <Element approvalStatus at 0x7f42d6a6e5c8>, <Element saleStatus at 0x7f42d6a6e608>, <Element stockItems at 0x7f42d6a6e648>, <Element subtitle at 0x7f42d6a6e688>, <Element title at 0x7f42d6a6e6c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('144.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6e748>, <Element id at 0x7f42d6a6e788>, <Element price at 0x7f42d6a6e7c8>, <Element productSellerCode at 0x7f42d6a6e808>, <Element approvalStatus at 0x7f42d6a6e848>, <Element saleStatus at 0x7f42d6a6e888>, <Element stockItems at 0x7f42d6a6e8c8>, <Element subtitle at 0x7f42d6a6e908>, <Element title at 0x7f42d6a6e948>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('408.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6e9c8>, <Element id at 0x7f42d6a6ea08>, <Element price at 0x7f42d6a6ea48>, <Element productSellerCode at 0x7f42d6a6ea88>, <Element approvalStatus at 0x7f42d6a6eac8>, <Element saleStatus at 0x7f42d6a6eb08>, <Element stockItems at 0x7f42d6a6eb48>, <Element subtitle at 0x7f42d6a6eb88>, <Element title at 0x7f42d6a6ebc8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('408.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6ec48>, <Element id at 0x7f42d6a6ec88>, <Element price at 0x7f42d6a6ecc8>, <Element productSellerCode at 0x7f42d6a6ed08>, <Element approvalStatus at 0x7f42d6a6ed48>, <Element saleStatus at 0x7f42d6a6ed88>, <Element stockItems at 0x7f42d6a6edc8>, <Element subtitle at 0x7f42d6a6ee08>, <Element title at 0x7f42d6a6ee48>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('600.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a6eec8>, <Element id at 0x7f42d6a6ef08>, <Element price at 0x7f42d6a6ef48>, <Element productSellerCode at 0x7f42d6a6ef88>, <Element approvalStatus at 0x7f42d6a6efc8>, <Element saleStatus at 0x7f42d6a70048>, <Element stockItems at 0x7f42d6a70088>, <Element subtitle at 0x7f42d6a700c8>, <Element title at 0x7f42d6a70108>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('600.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a70188>, <Element id at 0x7f42d6a701c8>, <Element price at 0x7f42d6a70208>, <Element productSellerCode at 0x7f42d6a70248>, <Element approvalStatus at 0x7f42d6a70288>, <Element saleStatus at 0x7f42d6a702c8>, <Element stockItems at 0x7f42d6a70308>, <Element subtitle at 0x7f42d6a70348>, <Element title at 0x7f42d6a70388>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('420.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a70408>, <Element id at 0x7f42d6a70448>, <Element price at 0x7f42d6a70488>, <Element productSellerCode at 0x7f42d6a704c8>, <Element approvalStatus at 0x7f42d6a70508>, <Element saleStatus at 0x7f42d6a70548>, <Element stockItems at 0x7f42d6a70588>, <Element subtitle at 0x7f42d6a705c8>, <Element title at 0x7f42d6a70608>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('420.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a70688>, <Element id at 0x7f42d6a706c8>, <Element price at 0x7f42d6a70708>, <Element productSellerCode at 0x7f42d6a70748>, <Element approvalStatus at 0x7f42d6a70788>, <Element saleStatus at 0x7f42d6a707c8>, <Element stockItems at 0x7f42d6a70808>, <Element subtitle at 0x7f42d6a70848>, <Element title at 0x7f42d6a70888>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('1080.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a70908>, <Element id at 0x7f42d6a70948>, <Element price at 0x7f42d6a70988>, <Element productSellerCode at 0x7f42d6a709c8>, <Element approvalStatus at 0x7f42d6a70a08>, <Element saleStatus at 0x7f42d6a70a48>, <Element stockItems at 0x7f42d6a70a88>, <Element subtitle at 0x7f42d6a70ac8>, <Element title at 0x7f42d6a70b08>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('1080.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a70b88>, <Element id at 0x7f42d6a70bc8>, <Element price at 0x7f42d6a70c08>, <Element productSellerCode at 0x7f42d6a70c48>, <Element approvalStatus at 0x7f42d6a70c88>, <Element saleStatus at 0x7f42d6a70cc8>, <Element stockItems at 0x7f42d6a70d08>, <Element subtitle at 0x7f42d6a70d48>, <Element title at 0x7f42d6a70d88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('720.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a70e08>, <Element id at 0x7f42d6a70e48>, <Element price at 0x7f42d6a70e88>, <Element productSellerCode at 0x7f42d6a70ec8>, <Element approvalStatus at 0x7f42d6a70f08>, <Element saleStatus at 0x7f42d6a70f48>, <Element stockItems at 0x7f42d6a70f88>, <Element subtitle at 0x7f42d6a70fc8>, <Element title at 0x7f42d6a72048>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('720.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a720c8>, <Element id at 0x7f42d6a72108>, <Element price at 0x7f42d6a72148>, <Element productSellerCode at 0x7f42d6a72188>, <Element approvalStatus at 0x7f42d6a721c8>, <Element saleStatus at 0x7f42d6a72208>, <Element stockItems at 0x7f42d6a72248>, <Element subtitle at 0x7f42d6a72288>, <Element title at 0x7f42d6a722c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('126.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a72348>, <Element id at 0x7f42d6a72388>, <Element price at 0x7f42d6a723c8>, <Element productSellerCode at 0x7f42d6a72408>, <Element approvalStatus at 0x7f42d6a72448>, <Element saleStatus at 0x7f42d6a72488>, <Element stockItems at 0x7f42d6a724c8>, <Element subtitle at 0x7f42d6a72508>, <Element title at 0x7f42d6a72548>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('126.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a725c8>, <Element id at 0x7f42d6a72608>, <Element price at 0x7f42d6a72648>, <Element productSellerCode at 0x7f42d6a72688>, <Element approvalStatus at 0x7f42d6a726c8>, <Element saleStatus at 0x7f42d6a72708>, <Element stockItems at 0x7f42d6a72748>, <Element subtitle at 0x7f42d6a72788>, <Element title at 0x7f42d6a727c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('156.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a72848>, <Element id at 0x7f42d6a72888>, <Element price at 0x7f42d6a728c8>, <Element productSellerCode at 0x7f42d6a72908>, <Element approvalStatus at 0x7f42d6a72948>, <Element saleStatus at 0x7f42d6a72988>, <Element stockItems at 0x7f42d6a729c8>, <Element subtitle at 0x7f42d6a72a08>, <Element title at 0x7f42d6a72a48>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('156.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a72ac8>, <Element id at 0x7f42d6a72b08>, <Element price at 0x7f42d6a72b48>, <Element productSellerCode at 0x7f42d6a72b88>, <Element approvalStatus at 0x7f42d6a72bc8>, <Element saleStatus at 0x7f42d6a72c08>, <Element stockItems at 0x7f42d6a72c48>, <Element subtitle at 0x7f42d6a72c88>, <Element title at 0x7f42d6a72cc8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('480.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a72d48>, <Element id at 0x7f42d6a72d88>, <Element price at 0x7f42d6a72dc8>, <Element productSellerCode at 0x7f42d6a72e08>, <Element approvalStatus at 0x7f42d6a72e48>, <Element saleStatus at 0x7f42d6a72e88>, <Element stockItems at 0x7f42d6a72ec8>, <Element subtitle at 0x7f42d6a72f08>, <Element title at 0x7f42d6a72f48>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('480.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a72fc8>, <Element id at 0x7f42d6a74048>, <Element price at 0x7f42d6a74088>, <Element productSellerCode at 0x7f42d6a740c8>, <Element approvalStatus at 0x7f42d6a74108>, <Element saleStatus at 0x7f42d6a74148>, <Element stockItems at 0x7f42d6a74188>, <Element subtitle at 0x7f42d6a741c8>, <Element title at 0x7f42d6a74208>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('960.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a74288>, <Element id at 0x7f42d6a742c8>, <Element price at 0x7f42d6a74308>, <Element productSellerCode at 0x7f42d6a74348>, <Element approvalStatus at 0x7f42d6a74388>, <Element saleStatus at 0x7f42d6a743c8>, <Element stockItems at 0x7f42d6a74408>, <Element subtitle at 0x7f42d6a74448>, <Element title at 0x7f42d6a74488>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('960.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a74508>, <Element id at 0x7f42d6a74548>, <Element price at 0x7f42d6a74588>, <Element productSellerCode at 0x7f42d6a745c8>, <Element approvalStatus at 0x7f42d6a74608>, <Element saleStatus at 0x7f42d6a74648>, <Element stockItems at 0x7f42d6a74688>, <Element subtitle at 0x7f42d6a746c8>, <Element title at 0x7f42d6a74708>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('252.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a74788>, <Element id at 0x7f42d6a747c8>, <Element price at 0x7f42d6a74808>, <Element productSellerCode at 0x7f42d6a74848>, <Element approvalStatus at 0x7f42d6a74888>, <Element saleStatus at 0x7f42d6a748c8>, <Element stockItems at 0x7f42d6a74908>, <Element subtitle at 0x7f42d6a74948>, <Element title at 0x7f42d6a74988>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('252.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a74a08>, <Element id at 0x7f42d6a74a48>, <Element price at 0x7f42d6a74a88>, <Element productSellerCode at 0x7f42d6a74ac8>, <Element approvalStatus at 0x7f42d6a74b08>, <Element saleStatus at 0x7f42d6a74b48>, <Element stockItems at 0x7f42d6a74b88>, <Element subtitle at 0x7f42d6a74bc8>, <Element title at 0x7f42d6a74c08>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('120.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a74c88>, <Element id at 0x7f42d6a74cc8>, <Element price at 0x7f42d6a74d08>, <Element productSellerCode at 0x7f42d6a74d48>, <Element approvalStatus at 0x7f42d6a74d88>, <Element saleStatus at 0x7f42d6a74dc8>, <Element stockItems at 0x7f42d6a74e08>, <Element subtitle at 0x7f42d6a74e48>, <Element title at 0x7f42d6a74e88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('120.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a74f08>, <Element id at 0x7f42d6a74f48>, <Element price at 0x7f42d6a74f88>, <Element productSellerCode at 0x7f42d6a74fc8>, <Element approvalStatus at 0x7f42d6a75048>, <Element saleStatus at 0x7f42d6a75088>, <Element stockItems at 0x7f42d6a750c8>, <Element subtitle at 0x7f42d6a75108>, <Element title at 0x7f42d6a75148>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('144.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a751c8>, <Element id at 0x7f42d6a75208>, <Element price at 0x7f42d6a75248>, <Element productSellerCode at 0x7f42d6a75288>, <Element approvalStatus at 0x7f42d6a752c8>, <Element saleStatus at 0x7f42d6a75308>, <Element stockItems at 0x7f42d6a75348>, <Element subtitle at 0x7f42d6a75388>, <Element title at 0x7f42d6a753c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('144.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a75448>, <Element id at 0x7f42d6a75488>, <Element price at 0x7f42d6a754c8>, <Element productSellerCode at 0x7f42d6a75508>, <Element approvalStatus at 0x7f42d6a75548>, <Element saleStatus at 0x7f42d6a75588>, <Element stockItems at 0x7f42d6a755c8>, <Element subtitle at 0x7f42d6a75608>, <Element title at 0x7f42d6a75648>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('408.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a756c8>, <Element id at 0x7f42d6a75708>, <Element price at 0x7f42d6a75748>, <Element productSellerCode at 0x7f42d6a75788>, <Element approvalStatus at 0x7f42d6a757c8>, <Element saleStatus at 0x7f42d6a75808>, <Element stockItems at 0x7f42d6a75848>, <Element subtitle at 0x7f42d6a75888>, <Element title at 0x7f42d6a758c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('408.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a75948>, <Element id at 0x7f42d6a75988>, <Element price at 0x7f42d6a759c8>, <Element productSellerCode at 0x7f42d6a75a08>, <Element approvalStatus at 0x7f42d6a75a48>, <Element saleStatus at 0x7f42d6a75a88>, <Element stockItems at 0x7f42d6a75ac8>, <Element subtitle at 0x7f42d6a75b08>, <Element title at 0x7f42d6a75b48>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('408.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a75bc8>, <Element id at 0x7f42d6a75c08>, <Element price at 0x7f42d6a75c48>, <Element productSellerCode at 0x7f42d6a75c88>, <Element approvalStatus at 0x7f42d6a75cc8>, <Element saleStatus at 0x7f42d6a75d08>, <Element stockItems at 0x7f42d6a75d48>, <Element subtitle at 0x7f42d6a75d88>, <Element title at 0x7f42d6a75dc8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('69.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a75e48>, <Element id at 0x7f42d6a75e88>, <Element price at 0x7f42d6a75ec8>, <Element productSellerCode at 0x7f42d6a75f08>, <Element approvalStatus at 0x7f42d6a75f48>, <Element saleStatus at 0x7f42d6a75f88>, <Element stockItems at 0x7f42d6a75fc8>, <Element subtitle at 0x7f42d6a77048>, <Element title at 0x7f42d6a77088>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('69.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a77108>, <Element id at 0x7f42d6a77148>, <Element price at 0x7f42d6a77188>, <Element productSellerCode at 0x7f42d6a771c8>, <Element approvalStatus at 0x7f42d6a77208>, <Element saleStatus at 0x7f42d6a77248>, <Element stockItems at 0x7f42d6a77288>, <Element subtitle at 0x7f42d6a772c8>, <Element title at 0x7f42d6a77308>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('69.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a77388>, <Element id at 0x7f42d6a773c8>, <Element price at 0x7f42d6a77408>, <Element productSellerCode at 0x7f42d6a77448>, <Element approvalStatus at 0x7f42d6a77488>, <Element saleStatus at 0x7f42d6a774c8>, <Element stockItems at 0x7f42d6a77508>, <Element subtitle at 0x7f42d6a77548>, <Element title at 0x7f42d6a77588>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('69.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a77608>, <Element id at 0x7f42d6a77648>, <Element price at 0x7f42d6a77688>, <Element productSellerCode at 0x7f42d6a776c8>, <Element approvalStatus at 0x7f42d6a77708>, <Element saleStatus at 0x7f42d6a77748>, <Element stockItems at 0x7f42d6a77788>, <Element subtitle at 0x7f42d6a777c8>, <Element title at 0x7f42d6a77808>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('84.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a77888>, <Element id at 0x7f42d6a778c8>, <Element price at 0x7f42d6a77908>, <Element productSellerCode at 0x7f42d6a77948>, <Element approvalStatus at 0x7f42d6a77988>, <Element saleStatus at 0x7f42d6a779c8>, <Element stockItems at 0x7f42d6a77a08>, <Element subtitle at 0x7f42d6a77a48>, <Element title at 0x7f42d6a77a88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('84.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a77b08>, <Element id at 0x7f42d6a77b48>, <Element price at 0x7f42d6a77b88>, <Element productSellerCode at 0x7f42d6a77bc8>, <Element approvalStatus at 0x7f42d6a77c08>, <Element saleStatus at 0x7f42d6a77c48>, <Element stockItems at 0x7f42d6a77c88>, <Element subtitle at 0x7f42d6a77cc8>, <Element title at 0x7f42d6a77d08>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('84.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a77d88>, <Element id at 0x7f42d6a77dc8>, <Element price at 0x7f42d6a77e08>, <Element productSellerCode at 0x7f42d6a77e48>, <Element approvalStatus at 0x7f42d6a77e88>, <Element saleStatus at 0x7f42d6a77ec8>, <Element stockItems at 0x7f42d6a77f08>, <Element subtitle at 0x7f42d6a77f48>, <Element title at 0x7f42d6a77f88>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('84.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a79048>, <Element id at 0x7f42d6a79088>, <Element price at 0x7f42d6a790c8>, <Element productSellerCode at 0x7f42d6a79108>, <Element approvalStatus at 0x7f42d6a79148>, <Element saleStatus at 0x7f42d6a79188>, <Element stockItems at 0x7f42d6a791c8>, <Element subtitle at 0x7f42d6a79208>, <Element title at 0x7f42d6a79248>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('108.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a792c8>, <Element id at 0x7f42d6a79308>, <Element price at 0x7f42d6a79348>, <Element productSellerCode at 0x7f42d6a79388>, <Element approvalStatus at 0x7f42d6a793c8>, <Element saleStatus at 0x7f42d6a79408>, <Element stockItems at 0x7f42d6a79448>, <Element subtitle at 0x7f42d6a79488>, <Element title at 0x7f42d6a794c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('108.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a79548>, <Element id at 0x7f42d6a79588>, <Element price at 0x7f42d6a795c8>, <Element productSellerCode at 0x7f42d6a79608>, <Element approvalStatus at 0x7f42d6a79648>, <Element saleStatus at 0x7f42d6a79688>, <Element stockItems at 0x7f42d6a796c8>, <Element subtitle at 0x7f42d6a79708>, <Element title at 0x7f42d6a79748>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('59.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a797c8>, <Element id at 0x7f42d6a79808>, <Element price at 0x7f42d6a79848>, <Element productSellerCode at 0x7f42d6a79888>, <Element approvalStatus at 0x7f42d6a798c8>, <Element saleStatus at 0x7f42d6a79908>, <Element stockItems at 0x7f42d6a79948>, <Element subtitle at 0x7f42d6a79988>, <Element title at 0x7f42d6a799c8>])
            },
            {
                'id': None,
                'productSellerCode': None,
                'title': None,
                'subtitle': None,
                'price': None,
                'displayPrice': None,
                'saleStatus': None,
                'approvalStatus': None,
                'stockItems': None,
                'oldPrice': None,
                'currencyAmount': Decimal('59.00'),
                'currencyType': 1,
                '_raw_elements': deque([<Element displayPrice at 0x7f42d6a79a48>, <Element id at 0x7f42d6a79a88>, <Element price at 0x7f42d6a79ac8>, <Element productSellerCode at 0x7f42d6a79b08>, <Element approvalStatus at 0x7f42d6a79b48>, <Element saleStatus at 0x7f42d6a79b88>, <Element stockItems at 0x7f42d6a79bc8>, <Element subtitle at 0x7f42d6a79c08>, <Element title at 0x7f42d6a79c48>])
            }
        ]
    },
    'pagingData': {
        'currentPage': 0,
        'pageSize': 100,
        'totalCount': 1858,
        'pageCount': 19
    }
}

"""

print((len(input)))


"""
d = collections.OrderedDict()
x = 0

for x in range(1,10):
	d[str(x)] = ["thisis " + str(x * 10)]
	pass


for k,v in d.items():
	print (k, v)
	print(type(v)) #v nin tipi list 
#print(d['1'])
#print(d)
"""